### ISSUE TITLE
リスト: 夜間モードにおけるダッシュボードを修正する

### ISSUE THREAD

**Issue by shion255** [AviSynthPlus/twiFixWebLite#1]
![image](https://user-images.githubusercontent.com/42429571/46080132-0a030e00-c1d4-11e8-9fc7-3660cf307bc2.png)
```css
div.follow-bar.js-list-actions { box-shadow: inset 0 1px 0 #fff; }
```

**Comment by AviSynthPlus** [comment]
![image](https://user-images.githubusercontent.com/42429571/46080190-33239e80-c1d4-11e8-9244-97ca74d0224a.png)
```css
[data-component-context="list_follow_card"] .js-list-actions {
    box-shadow: none !important;
    border-width: 0 1px 1px 1px !important;
    border-color: rgb(56, 68, 77) !important;
  }
```

**Comment by AviSynthPlus** [comment]
![image](https://user-images.githubusercontent.com/42429571/46080190-33239e80-c1d4-11e8-9244-97ca74d0224a.png)
```css
[data-component-context="list_follow_card"] .js-list-actions {
    box-shadow: none !important;
    border-width: 0 1px 1px 1px !important;
    border-color: rgb(56, 68, 77) !important;
}
```

**Comment by shion255** [comment]
![image](https://user-images.githubusercontent.com/42429571/46080190-33239e80-c1d4-11e8-9244-97ca74d0224a.png)
```css
[data-component-context="list_follow_card"] .js-list-actions {
  box-shadow: none !important;
  border-width: 0 1px 1px 1px !important;
  border-color: rgb(56, 68, 77) !important;
}
```
