### ISSUE TITLE
メッセージ: 絵文字ピッカーにスクロールバーが重なる問題を修正する

### ISSUE THREAD

**Issue by shion255** [AviSynthPlus/twiFixWebLite#2]
![a](https://user-images.githubusercontent.com/42429571/46329018-dac22600-c645-11e8-91c2-3f25d33105c9.png)
---
![b](https://user-images.githubusercontent.com/42429571/46329028-e7467e80-c645-11e8-9a92-54ef5fcceba5.png)
**Firefox**

![c](https://user-images.githubusercontent.com/42429571/46329040-ff1e0280-c645-11e8-9540-6f7744300fad.png)
**Chrome**

**Comment by AviSynthPlus** [comment]
余計に悪化したので
``` css
.DMComposer .EmojiPicker {
    margin-right: 10px !important;
  }
```
に戻した

**Comment by shion255** [comment]
余計に悪化したので
``` css
.DMComposer .EmojiPicker {
    margin-right: 10px !important;
}
```
に戻した
